### ISSUE TITLE
[Issue]: AutoML doesn' work in Microsoft Fabric

### ISSUE THREAD

**Issue by rnavarromatesanz** [microsoft/FLAML#1346]
### Describe the issue

Hi Flaml team,

I'm having an issue with the AutoML functionlity in Fabric (trial).

Several months ago (around 4 or 5), I followed the example provided on Microsoft Learn (https://learn.microsoft.com/en-us/fabric/data-science/how-to-use-automated-machine-learning-fabric), and it worked perfectly. However, when I tried to execute it again a couple of months ago, I encountered issues with the FLAML library. Considering that this feature is still in preview, I decided to wait. Unfortunately, when I tested it again a couple of week ago, I encountered the same problem.

Trying to solve the problem and executing "help(mmodules)" I had this message

--------------------------------------------------------------------
****** AutoML Prerequisites ******

AutoML requires an Apache Spark pool (version 2.4) in your Azure Synapse Analytics workspace.

You are using a Spark 3.x pool, please use Spark 2.x pool. For details, see: [https://docs.microsoft.com/en-us/azure/synapse-analytics/machine-learning/tutorial-automl#prerequisi...](https://docs.microsoft.com/en-us/azure/synapse-analytics/machine-learning/tutorial-automl#prerequisites)

---------------------------------------------------------------------

And in MS Fabric only works with Spark 3.2 and upper pools. any workaround or planning to support the new Spark pools?

Regards and Thanks in advance

### Steps to reproduce

In a notebook of Fabric

This is the code

# Import the AutoML class from the FLAML package
from flaml import AutoML
# Create an AutoML instance
automl = AutoML()
 

### Screenshots and logs

And this is the error
---------------------------------------------------------------------------
ImportError Traceback (most recent call last)
Cell In[52], line 2
1 # Import the AutoML class from the FLAML package
----> 2 from flaml import AutoML
3 # Create an AutoML instance
4 automl = AutoML()
ImportError: cannot import name 'AutoML' from 'flaml' (unknown location)

**Comment by thinkall** [comment]
Hi @rnavarromatesanz , FLAML is not installed in Synapse by default, you can install the open source version by yourself, but there is no autologging and some other feature supports as documented [here](https://learn.microsoft.com/en-us/fabric/data-science/automated-machine-learning-fabric). [Azure Synapse Analytics](https://azure.microsoft.com/en-us/products/synapse-analytics) is not the same product as [Microsoft Fabric](https://www.microsoft.com/en-us/microsoft-fabric). You should be able to use AutoML solution in Fabric. Let me know if you encountered any issue in Fabric. Thank you.

**Comment by rnavarromatesanz** [comment]
Hi @thinkall 

Sorry for the delay, it seems that was something related with my workspace in Fabric and not with Flaml...

Thanks for your response
