### ISSUE TITLE
The ensemble option in the main fit function does not work with customized learners

### ISSUE THREAD

**Issue by flippercy** [microsoft/FLAML#18]
I fit a model with both the RGF in the sample codes and a few other default learners:

settings = {
    "time_budget": 120, # total running time in seconds
    "metric": 'roc_auc', 
    "estimator_list": ['lgbm', 'rf', 'RGF'], # list of ML learners
    "task": 'classification', # task type    
    "sample": True, # whether to subsample training data
    "log_file_name": 'airlines_experiment_with_ensemble.log', # cache directory of flaml log files 
    "log_training_metric": True, # whether to log training metric
}
automl.fit(X_train = X_train, y_train = y_train, ensemble=True, **settings)

I received an error message:  TypeError: __init__() got an unexpected keyword argument '_estimator_type'

I got similar results when using other customized learners with unique hyperparameters.

Moreover, how can I pull the details of the ensemble? I did not see it in the log file.

Thank you.

**Comment by flippercy** [comment]
Actually, it seems that the ensemble option does not work whenever the estimator_list is specified. For example:

settings = {
    "time_budget": 40, # total running time in seconds
    "metric": 'roc_auc', 
    "estimator_list": ['lgbm', 'xgboost'], # list of ML learners
    "task": 'classification', # task type    
    "sample": False, # whether to subsample training data
    "log_file_name": 'airlines_experiment_with_ensemble.log', # cache directory of flaml log files 
    "log_training_metric": False, # whether to log training metric
}

automl.fit(X_train = X_train, y_train = y_train, ensemble=True, **settings)

AttributeError: 'XGBoostSklearnEstimator' object has no attribute 'n_features_in_'

**Comment by sonichi** [comment]
Could you let me know the version of sklearn you are using?

**Comment by flippercy** [comment]
I am using 0.23.1.

**Comment by sonichi** [comment]
I can reproduce the problem in 0.23.1 but it works in 0.23.2. 
It seems to be a problem of scikit-learn: https://github.com/scikit-learn/scikit-learn/issues/17353

**Comment by flippercy** [comment]
Thank you! Waiting for the next release of FLAML!

Best,
